import {
  fullName,
  fullNameInfo,
  itAccessories,
  lvlInfo,
  lvlUrgency,
  note,
  noteInfo,
  selectInfo,
  submitBtn,
  typeButton,
  typeInput,
  typeMultipleSelect,
  typeSelect,
  typeTextarea,
} from 'features/constants'

const listMaterials = [
  {
    id: 1,
    label: fullName,
    tooltip: true,
    nameStore: fullName,
    required: true,
    message: fullNameInfo,
    whitespace: true,
    typeField: typeInput,
  },
  {
    id: 2,
    label: typeSelect,
    tooltip: false,
    nameStore: lvlUrgency,
    required: true,
    message: lvlInfo,
    typeField: typeSelect,
    typeSelectOption: '',
    selectOption: ['Low', 'Medium', 'High'],
  },

  {
    id: 4,
    label: typeMultipleSelect,
    tooltip: false,
    nameStore: itAccessories,
    required: true,
    message: selectInfo,
    typeSelectOption: 'array',
    typeField: typeMultipleSelect,
    selectOption: [
      'Backpack',
      'Network cable',
      'Laptop Charger',
      'Extension card',
      'Headset',
      'Mouse',
      'Keyboard',
      'Laptop riser/cooler',
      'UK/EU outlet adaptor',
      'Video adaptor',
    ],
  },
  {
    id: 5,
    label: note,
    tooltip: true,
    nameStore: note,
    required: false,
    message: noteInfo,
    whitespace: false,
    typeField: typeTextarea,
  },
  {
    id: 6,
    label: submitBtn,
    tooltip: false,
    type: 'primary',
    htmlType: 'submit',
    typeField: typeButton,
  },
]

export default listMaterials
